--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.1.1112
--  Created On : Monday, 02 February, 2015 
--  DBMS       : DB2 
--  -------------------------------------------------- 

DROP TABLE PARTY
;

-- START SNIPPET: PARTY-DDL
CREATE TABLE PARTY ( 
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	founded_year INTEGER NOT NULL
	CHECK (founded_year BETWEEN 1789 AND 9999),
	end_year INTEGER
	CHECK (end_year BETWEEN 1789 AND 9999)
);

ALTER TABLE PARTY ADD CONSTRAINT PK_Party 
 PRIMARY KEY (id)
;


ALTER TABLE PARTY
	ADD CONSTRAINT UQ_PARTY_name UNIQUE (name)
;
-- END SNIPPET: PARTY-DDL