ALTER TABLE PRESIDENT DROP CONSTRAINT FK_PRESIDENT_STATE;
ALTER TABLE PRESIDENT DROP CONSTRAINT FK_PRESIDENT_PARTY;
DROP VIEW PRESIDENTS_VIEW;
DROP TABLE STATE;
DROP TABLE PARTY;
DROP TABLE PRESIDENT;
