INSERT INTO state (name,abbreviation) VALUES ('Alabama','AL');
INSERT INTO state (name,abbreviation) VALUES ('Alaska','AK');
INSERT INTO state (name,abbreviation) VALUES ('Arizona','AZ');
INSERT INTO state (name,abbreviation) VALUES ('Arkansas','AR');
INSERT INTO state (name,abbreviation) VALUES ('California','CA');
INSERT INTO state (name,abbreviation) VALUES ('Colorado','CO');
INSERT INTO state (name,abbreviation) VALUES ('Connecticut','CT');
INSERT INTO state (name,abbreviation) VALUES ('Delaware','DE');
INSERT INTO state (name,abbreviation) VALUES ('Florida','FL');
INSERT INTO state (name,abbreviation) VALUES ('Georgia','GA');
INSERT INTO state (name,abbreviation) VALUES ('Hawaii','HI');
INSERT INTO state (name,abbreviation) VALUES ('Idaho','ID');
INSERT INTO state (name,abbreviation) VALUES ('Illinois','IL');
INSERT INTO state (name,abbreviation) VALUES ('Indiana','IN');
INSERT INTO state (name,abbreviation) VALUES ('Iowa','IA');
INSERT INTO state (name,abbreviation) VALUES ('Kansas','KS');
INSERT INTO state (name,abbreviation) VALUES ('Kentucky','KY');
INSERT INTO state (name,abbreviation) VALUES ('Louisiana','LA');
INSERT INTO state (name,abbreviation) VALUES ('Maine','ME');
INSERT INTO state (name,abbreviation) VALUES ('Maryland','MD');
INSERT INTO state (name,abbreviation) VALUES ('Massachusetts','MA');
INSERT INTO state (name,abbreviation) VALUES ('Michigan','MI');
INSERT INTO state (name,abbreviation) VALUES ('Minnesota','MN');
INSERT INTO state (name,abbreviation) VALUES ('Mississippi','MS');
INSERT INTO state (name,abbreviation) VALUES ('Missouri','MO');
INSERT INTO state (name,abbreviation) VALUES ('Montana','MT');
INSERT INTO state (name,abbreviation) VALUES ('Nebraska','NE');
INSERT INTO state (name,abbreviation) VALUES ('Nevada','NV');
INSERT INTO state (name,abbreviation) VALUES ('New Hampshire','NH');
INSERT INTO state (name,abbreviation) VALUES ('New Jersey','NJ');
INSERT INTO state (name,abbreviation) VALUES ('New Mexico','NM');
INSERT INTO state (name,abbreviation) VALUES ('New York','NY');
INSERT INTO state (name,abbreviation) VALUES ('North Carolina','NC');
INSERT INTO state (name,abbreviation) VALUES ('North Dakota','ND');
INSERT INTO state (name,abbreviation) VALUES ('Ohio','OH');
INSERT INTO state (name,abbreviation) VALUES ('Oklahoma','OK');
INSERT INTO state (name,abbreviation) VALUES ('Oregon','OR');
INSERT INTO state (name,abbreviation) VALUES ('Pennsylvania','PA');
INSERT INTO state (name,abbreviation) VALUES ('Rhode Island','RI');
INSERT INTO state (name,abbreviation) VALUES ('South Carolina','SC');
INSERT INTO state (name,abbreviation) VALUES ('South Dakota','SD');
INSERT INTO state (name,abbreviation) VALUES ('Tennessee','TN');
INSERT INTO state (name,abbreviation) VALUES ('Texas','TX');
INSERT INTO state (name,abbreviation) VALUES ('Utah','UT');
INSERT INTO state (name,abbreviation) VALUES ('Vermont','VT');
INSERT INTO state (name,abbreviation) VALUES ('Virginia','VA');
INSERT INTO state (name,abbreviation) VALUES ('Washington','WA');
INSERT INTO state (name,abbreviation) VALUES ('West Virginia','WV');
INSERT INTO state (name,abbreviation) VALUES ('Wisconsin','WI');
INSERT INTO state (name,abbreviation) VALUES ('Wyoming','WY');
