--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.1.1112
--  Created On : Monday, 02 February, 2015 
--  DBMS       : DB2 
--  -------------------------------------------------- 

DROP TABLE STATE
;
-- START SNIPPET: STATE-DDL
CREATE TABLE STATE ( 
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	abbreviation VARCHAR(255) NOT NULL
)
;

ALTER TABLE STATE ADD CONSTRAINT PK_STATE 
	PRIMARY KEY (id)
;

ALTER TABLE STATE
	ADD CONSTRAINT UQ_STATE_abbreviation UNIQUE (abbreviation)
;
ALTER TABLE STATE
	ADD CONSTRAINT UQ_STATE_name UNIQUE (name)
;
-- END SNIPPET: STATE-DDL

